import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { Nav } from "@/components/Nav";
import RecoilProvider from "./RecoilProvider";
import MantineProvider from "./MantineProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <RecoilProvider>
            <MantineProvider>
              <Nav />
              <div className="w-[100%] h-[100vh]">{children}</div>
            </MantineProvider>
          </RecoilProvider>
        </div>
      </body>
    </html>
  );
}
